const emuladores = [
    {
      id: 1,
      nome: "ZSNES",
      console: "Super Nintendo Entertainment System (SNES)",
      versao: "1.51",
      plataforma: "Windows, Linux, DOS",
      jogos: ["Super Mario World", "Chrono Trigger", "The Legend of Zelda: A Link to the Past"],
      desenvolvedor: "ZSNES Team",
      opensource: true,
      status: "Abandonado",
    },
    {
      id: 2,
      nome: "PCSX2",
      console: "PlayStation 2",
      versao: "1.6.0",
      plataforma: "Windows, macOS, Linux",
      jogos: ["God of War", "Final Fantasy X", "Shadow of the Colossus"],
      desenvolvedor: "PCSX2 Team",
      opensource: true,
      status: "Desenvolvimento",
    },
    {
      id: 3,
      nome: "Dolphin",
      console: "Nintendo GameCube e Wii",
      versao: "5.0",
      plataforma: "Windows, macOS, Linux, Android",
      jogos: ["Super Smash Bros. Melee", "The Legend of Zelda: Twilight Princess", "Metroid Prime"],
      desenvolvedor: "Dolphin Team",
      opensource: true,
      status: "Estável",
    },
    {
      id: 4,
      nome: "Citra",
      console: "Nintendo 3DS",
      versao: "1.0 (nightly)",
      plataforma: "Windows, macOS, Linux, Android",
      jogos: ["The Legend of Zelda: Ocarina of Time 3D", "Pokémon Sun and Moon", "Super Mario 3D Land"],
      desenvolvedor: "Citra Team",
      opensource: true,
      status: "Estável",
    },
    {
      id: 5,
      nome: "PPSSPP",
      console: "PlayStation Portable (PSP)",
      versao: "1.15.4",
      plataforma: "Windows, macOS, Linux, Android, iOS, Nintendo Switch",
      jogos: ["God of War: Chains of Olympus", "Grand Theft Auto: Liberty City Stories", "Monster Hunter Freedom Unite"],
      desenvolvedor: "Henrik Rydgård",
      opensource: true,
      status: "Estável",
    },
    {
      id: 6,
      nome: "MAME",
      console: "Vários sistemas de arcade",
      versao: "0.258",
      plataforma: "Windows, macOS, Linux",
      jogos: ["Pac-Man", "Street Fighter II", "Metal Slug"],
      desenvolvedor: "MAMEdev",
      opensource: true,
      status: "Desenvolvimento",
    },
    {
      id: 7,
      nome: "RetroArch",
      console: "Vários (front-end)",
      versao: "1.15.0",
      plataforma: "Windows, macOS, Linux, Android, iOS, consoles de videogame",
      jogos: ["(Depende do núcleo de emulação)"],
      desenvolvedor: "Libretro Team",
      opensource: true,
      status: "Estável",
    },
    {
      id: 8,
      nome: "ePSXe",
      console: "PlayStation",
      versao: "2.0.5",
      plataforma: "Windows, Android, Linux",
      jogos: ["Final Fantasy VII", "Crash Bandicoot", "Resident Evil 2"],
      desenvolvedor: "ePSXe Team",
      opensource: false,
      status: "Abandonado",
    },
    {
      id: 9,
      nome: "Visual Boy Advance",
      console: "Game Boy, Game Boy Color, Game Boy Advance",
      versao: "1.8.0-beta3",
      plataforma: "Windows, Linux, macOS",
      jogos: ["Pokémon FireRed", "The Legend of Zelda: The Minish Cap", "Metroid Fusion"],
      desenvolvedor: "VBA Team",
      opensource: true,
      status: "Abandonado",
    },
    {
      id: 10,
      nome: "Cemu",
      console: "Wii U",
      versao: "2.0-70",
      plataforma: "Windows, Linux",
      jogos: ["The Legend of Zelda: Breath of the Wild", "Super Mario 3D World", "Mario Kart 8"],
      desenvolvedor: "Exzap, Petergov",
      opensource: true,
      status: "Estável",
    },
  ];

  export default { emuladores };
  